apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  RESULTS_SINKS: {{ .Values.config.RESULTS_SINKS | quote }}
  RESULTS_FILE_PATH: {{ .Values.config.RESULTS_FILE_PATH | quote }}
  LOG_LEVEL: {{ .Values.config.LOG_LEVEL | quote }}
  {{- if .Values.s3.enabled }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
  S3_PREFIX: {{ .Values.s3.prefix | quote }}
  AWS_REGION: {{ .Values.s3.region | quote }}
  {{- end }}
